### ISSUE TITLE
OpenSSLPrivateKeyDecoder.Decode fails on .Net Core on Linux

### ISSUE THREAD

**Issue by LamarLugli** [StefH/OpenSSL-X509Certificate2-Provider#4]
If you call OpenSSLPrivateKeyDecoder.Decode running on .Net Core on Linux (or docker for windows), this call fails with 

> PlatformNotSupportedException: Operation is not supported on this platform

. 

The error happens on System.Security.Cryptography.RSACryptoServiceProvider..ctor() because RSACryptoServiceProvider is a windows-only concept.

I think it would be more compatible to return just the RSAParameters object instead of trying to wrap it with RSACryptoServiceProvider.

We could extend this with with a DecodeParams function that keeps all the inner logic but returns RSAParameter, and still have the existing Decode functions that just wrap that with RSACryptoServiceProvider.  

Alternatively, you could just return an RSA object, that on windows  I think just wraps RSACryptoServiceProvider.

I want to use this library but I'm stuck.

**Comment by StefH** [comment]
New NuGet is uploaded : https://www.nuget.org/packages/OpenSSL.PrivateKeyDecoder

And a question for you:
Can you provide some example code on how you can use this?
And also, what do you use as alternative for CryptoConfig.MapNameToOID("SHA256")?

**Comment by StefH** [comment]
BTW a better design would be:

`bool TryDecode(out RSACryptoServiceProvider provider)`
and
`bool TryDecode(out RSAParameters rsaParameters)`

**Comment by LamarLugli** [comment]
Thanks for the quick response.  I loaded the new Nuget package and the new function works great.

Here is the code I am using on Linux (asp.net core 1.1 in Docker) in case anyone is interested.

    var privateKeyText = File.ReadAllText(fullFileName);

    IOpenSSLPrivateKeyDecoder decoder = new OpenSSLPrivateKeyDecoder();
    var rsaParameters = decoder.DecodeParameters(privateKeyText);

    var key = new Microsoft.IdentityModel.Tokens.RsaSecurityKey(rsaParameters);
    var signingCredentials = new Microsoft.IdentityModel.Tokens.SigningCredentials(key, "RS256");

I don't know if I can help you with your question on CryptoConfig.MapNameToOID("SHA256") since I don't use that anywhere.
