### ISSUE TITLE
An exception about "The credentials supplied to the package were not recognized"

### ISSUE THREAD

**Issue by Elyhance** [StefH/OpenSSL-X509Certificate2-Provider#7]
Dear StefH

I'm developing a tls server now. I used OpenSSL-X509Certificate2-Provider to import .crt&.key, but when run to  AuthenticateAsServerAsync(), an exception occurred with error message"The credentials supplied to the package were not recognized". In the other hand, it works well by converted crt&key to pfx format through openssl tool. So what's wrong here? Is the RSA private key supported？ If not, i saw it in the source code.

**Comment by StefH** [comment]
Please provide a code example for this, I cannot understand what you want to do.

**Comment by Elyhance** [comment]
My code like this: 
``` c#
 string certificateText = File.ReadAllText("certificate_pub.crt");
 string privateKeyText = File.ReadAllText("private.key");

 ICertificateProvider provider = new CertificateFromFileProvider(certificateText, privateKeyText);
 X509Certificate2 SslCertificate = provider.Certificate;

 sslClient.Sstream = new SslStream(sslClient.Nstream, false);

 await sslClient.Sstream.AuthenticateAsServerAsync(SslCertificate, iMaumutually, UserProto, false);  // A client request to connect the server, an exception is thrown,"The credentials supplied to the package were not recognized"
```
 
But it works well through the way below:
`openssl pkcs12 -export -out {pfxName} -passout pass:{pfxPasswd} -inkey private.key -in certificate_pub.crt`
``` c#
var SslCertificate = new X509Certificate2(pfxName, pfxPasswd);
```
I used the same certificate.

**Comment by LamarLugli** [comment]
are you running on .net framework or .net core?  Windows or Linux?
when you create the SslCertificate object, is the HasPrivateKey property set?

**Comment by Elyhance** [comment]
Thank you for your quickly reply.
I am running on .net framework 4.5.2, windows 7 sp1. The HasPrivateKey property is  not set, and the private key dose not have password

**Comment by Fumi24** [comment]
@Elylhance Sorry to poke this thread after months, but did you ever manage to make it work? im getting the same error and my other options i to make a custom installer and make sure openssl is installed which i kinda dont wanna do.

**Comment by StefH** [comment]
@Fumi24 
@Elylhance 
@LammyL 

Can somebody please create a full example project with dummy private/public keys. (Or the commands on how to create it) ?

Else I cannot understand what's going wrong.

**Comment by StefH** [comment]
@nelsonjchen maybe you also have some ideas on this issue?

**Comment by nelsonjchen** [comment]
Wow! That looks like my issue in #9 somewhat. Even the throw the towel in and use a PFX workaround!

**Comment by nelsonjchen** [comment]
With #10 merged in, it would be interesting if the people experiencing this issue tried out the new constructor that'll store the key in a named container.

**Comment by StefH** [comment]
@Elylhance
@LamarLugli 
@Fumi24 
Does merging #10 solve this issue ?

**Comment by Elyhance** [comment]
@StefH I cannot load my certificates yet with the newest NuGet packet. 
Actually, it's the wolfSSL(CyaSSL)'s certificates for test.

[server-cert.pem.txt](https://github.com/StefH/OpenSSL-X509Certificate2-Provider/files/2344516/server-cert.pem.txt)
[server-key.pem.txt](https://github.com/StefH/OpenSSL-X509Certificate2-Provider/files/2344517/server-key.pem.txt)

**Comment by StefH** [comment]
@Elylhance 
For the `net452` example project, your server and private keys work fine?
See https://github.com/StefH/OpenSSL-X509Certificate2-Provider/blob/master/examples/ConsoleApp452/Demo.cs#L15

**Comment by Elyhance** [comment]
Maybe there is some wrong with my routine, but I have no time to solve it. So just close this issue.

**Comment by StefH** [comment]
OK. If you need more help in future, just create a new issue.
