### ISSUE TITLE
Best practice for using provider to load OpenSSL PEM files for HttpWebRequest client certificate authentication?

### ISSUE THREAD

**Issue by nelsonjchen** [StefH/OpenSSL-X509Certificate2-Provider#9]
I have to do this workaround to be able to use PEM certificates from this provider in `HttpWebRequest`:

```csharp
{
	var cspLessPrivateKey = provider.PrivateKey;
	CspParameters cspParameters = new CspParameters {KeyContainerName = $"{{{Guid.NewGuid().ToString()}}}"};
	var cspPrivateKey = new RSACryptoServiceProvider(cspParameters);
	cspPrivateKey.ImportParameters(cspLessPrivateKey.ExportParameters(true));
	certificate.PrivateKey = cspPrivateKey;
}
```

The `RSACryptoServiceProvider` needs to be replaced with a new `RSACryptoServiceProvider` that has a `KeyContainerName` set.

Is this a good practice? I'm trying to replicate the `X509Certificate2` constructor where you pass in a pfx or P12 file but with:

```csharp
var certificate =
    new X509Certificate2(@"C:\Users\User\Documents\HTTPClientCertDownload\HTTPClientCertDownload\export.p12");                
```

From what I can see, the `RSACryptoServiceProvider`s for the `PrivateKey` in that have a `$"{{{Guid.NewGuid().ToString()}}}"` as their key container names for that constructor.

Without the workaround, I get this error, which I assume is because the `PrivateKey` is not stored in some sort of accessible container to the `HttpWebRequest`:

```
Unhandled Exception: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at HTTPClientCertDownload.Program.Main(String[] args) in C:\Users\User\Documents\HTTPClientCertDownload\HTTPClientCertDownload\Program.cs:line 50
```

The PFX/PKCS12 certificate works fine though. I did do a sanity check with cURL though WSL and it loads the PEM files fine and establishes the TLS connection correctly and grabs the data from the test server.

## Full code

```csharp
using System;
using System.IO;
using System.Net;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using OpenSSL.X509Certificate2Provider;

namespace HTTPClientCertDownload
{
    static class Program
    {
        static void Main(string[] args)
        {
            string certificateText =
                File.ReadAllText(@"C:\Users\User\Documents\HTTPClientCertDownload\HTTPClientCertDownload\crt.pem");
            string privateKeyText =
                File.ReadAllText(@"C:\Users\User\Documents\HTTPClientCertDownload\HTTPClientCertDownload\key.pem");

            ICertificateProvider provider = new CertificateFromFileProvider(certificateText, privateKeyText);
            X509Certificate2 certificate = provider.Certificate;

            // Replace Private Key with Private Key stored in a named KeyContainer.
            // The block of code below patches up the PrivateKey to mimic enough of a PKCS12 Certificate import
            // where the PrivateKey is stored in a named CSP.
            {
                var cspLessPrivateKey = provider.PrivateKey;
                CspParameters cspParameters = new CspParameters {KeyContainerName = $"{{{Guid.NewGuid().ToString()}}}"};
                var cspPrivateKey = new RSACryptoServiceProvider(cspParameters);
                cspPrivateKey.ImportParameters(cspLessPrivateKey.ExportParameters(true));
                certificate.PrivateKey = cspPrivateKey;
            }

            HttpWebRequest req = (HttpWebRequest) WebRequest.Create(@"https://server.cryptomix.com/secure/");

            // Workaround for .NET 4.0
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = (SecurityProtocolType) 3072;
            req.PreAuthenticate = true;
            ServicePointManager.DefaultConnectionLimit = 9999;
            // Ignore Server Certificate
            ServicePointManager
                    .ServerCertificateValidationCallback +=
                (sender, cert, chain, sslPolicyErrors) => true;

            req.ClientCertificates.Add(certificate);

            HttpWebResponse response = (HttpWebResponse) req.GetResponse();

            var encoding = Encoding.ASCII;
            using (var reader = new StreamReader(response.GetResponseStream(), encoding))
            {
                string responseText = reader.ReadToEnd();
                Console.WriteLine(responseText);
            }
        }
    }
}
```

**Comment by StefH** [comment]
A possible solution could be that the constructor from CertificateFromFileProvider is extended like:

``` c#
public CertificateFromFileProvider([NotNull] string certificateText, [NotNull] string privateKeyText, bool useNamedKeyContainer= false, [CanBeNull] SecureString securePassword = null)
```
And that the code is updated like:
``` c#
if (useNamedKeyContainer)
{
    var cspParameters = new CspParameters { KeyContainerName = $"{{{Guid.NewGuid()}}}" };
    var cspPrivateKey = new RSACryptoServiceProvider(cspParameters);
    cspPrivateKey.ImportParameters(privateKey.ExportParameters(true));
    PrivateKey = cspPrivateKey;
}
else
{
    PrivateKey = privateKey;
}
```

Does this fit your requirements.

**Comment by nelsonjchen** [comment]
That would work and it would allow for non-Windows users to avoid that workaround since the whole `CSP` thing does not exist outside of that.

**Comment by StefH** [comment]
@nelsonjchen Please help me with a the correct name + description for `useNamedKeyContainer`.

**Comment by nelsonjchen** [comment]
I think it's an OK name. 

For description, maybe something like:

Set `useNamedKeyContainer` to `true` on Windows platforms to enable usage of the X509Certificate2 in SChannel based tasks. E.g. `HttpWebRequest`.

**Comment by nelsonjchen** [comment]
I'm also not on a Windows system at the moment, but it also might be worth slapping a breakpoint on the KeyParameters constructor and doing a normal `X509Certificate2` constructor with a PFX/P12 file, see how key parameters get called to have a GUID as a name, find the corresponding source, look at the comments for rationale, if any, and maybe consider making that the default on Windows. 

I'll probably do that in VM in a bit in my MacBook.

**Comment by nelsonjchen** [comment]
Also, the `X509Certificate2` neighboring area and friends is going through some sort of metamorphosis in implementation between .NET Framework and .NET Core. It appears to be mostly portability abstraction refactoring but I'll take a look there too.

**Comment by nelsonjchen** [comment]
Unfortunately, the implementation goes native for .NET's implementation so it's a bit too opaque. Not sure about the GUID thing. I think it's something the Windows API does automatically with the PFX loading API.

I also couldn't test the difference between .NET Core 2.1 as well. The private key is simply not loaded. That is probably an issue by itself. It also brings to mind a greater issue: Missing CI. 

Also, .NET Core 2.1 is also a bit opaque again. It's broken for this provider but with `X509Certificate(pfxFilename)`, I think they're calling a newer version of the Windows Crypto API but the result is very similar: A key name container of some sort with `Guid.NewGuid().ToString("B")`

**Comment by nelsonjchen** [comment]
I'll see if I can put up some demonstration projects tomorrow.

**Comment by StefH** [comment]
See the PR https://github.com/StefH/OpenSSL-X509Certificate2-Provider/tree/OpenSSLPEM where I already added a working HTTPClientCertDownload example project. 

Maybe you can review this PR and if all is ok, I can create new NuGet.

**Comment by nelsonjchen** [comment]
Looks fine to me.
